export default {
  roots: ['<rootDir>/src'],
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.(js|ts|tsx)$': ['@swc/jest', { jsc: { transform: { react: { runtime: 'automatic' } } } }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!aggregate-error|clean-stack|escape-string-regexp|indent-string|p-map)',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  modulePaths: ['<rootDir>/src'],
  moduleFileExtensions: ['ts', 'tsx', 'js'],
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  moduleNameMapper: {
    '^(.*)\\.js$': '$1',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '^.+\\.svg$': 'jest-svg-transformer',
    '^@pages/(.*)$': '<rootDir>/src/pages/$1',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@type/(.*)$': '<rootDir>/src/type/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@locales/(.*)$': '<rootDir>/src/locales/$1',
    '^@i18n/(.*)$': '<rootDir>/src/i18n/$1',
    '@components/(.*)$': '<rootDir>/src/components/$1',
    '@store/(.*)$': '<rootDir>/src/store/$1',
    '@api/(.*)$': '<rootDir>/src/api/$1',
    '@styles/(.*)$': '<rootDir>/src/styles/$1',
  },
  testMatch: ['**/?(*)+(test).ts', '**/?(*)+(test).tsx'],
  resetMocks: true,
  setupFilesAfterEnv: ['<rootDir>/test/jest.setup.ts'],
};
