import VisibleOnGray from 'src/assets/icons/visible_on_gray.svg';
import VisibleOffGray from 'src/assets/icons/visible_off_gray.svg';
import UserWhite from 'src/assets/icons/user_white.svg';
import UserBlack from 'src/assets/icons/user_black.svg';
import UserActivePurple from 'src/assets/icons/user_active.svg';
import TorderLogoSymbol from 'src/assets/icons/torder_logo_symbol.svg';
import LogoTorder from 'src/assets/icons/torder_logo_short_white.svg';
import LogoTorderName from 'src/assets/icons/torder_logo_name_white.svg';
import ToggleOnBlack from 'src/assets/icons/toggle_on_black.svg';
import ToggleOffBlack from 'src/assets/icons/toggle_off_black.svg';
import Step3 from 'src/assets/icons/step_status_3.svg';
import Step2 from 'src/assets/icons/step_status_2.svg';
import Step1 from 'src/assets/icons/step_status_1.svg';
import LogoNaver from 'src/assets/icons/sns_naver.svg';
import LogoKakao from 'src/assets/icons/sns_kakaotalk.svg';
import LogoGoogle from 'src/assets/icons/sns_google.svg';
import LogoApple from 'src/assets/icons/sns_apple.svg';
import SettingWhite from 'src/assets/icons/setting_white.svg';
import SettingBlack from 'src/assets/icons/setting_black.svg';
import SettingActiveBlack from 'src/assets/icons/setting_active.svg';
import SearchWhite from 'src/assets/icons/search_white.svg';
import SearchBlack from 'src/assets/icons/search_black.svg';
import SearchBackgroundBlack from 'src/assets/icons/search_background_black.svg';
import PlusBackgroundBlack from 'src/assets/icons/plus_background_black.svg';
import OpenWhite from 'src/assets/icons/open_white.svg';
import OpenNavy from 'src/assets/icons/open_navy.svg';
import NotificationWhite from 'src/assets/icons/notification_white.svg';
import NotificationBlack from 'src/assets/icons/notification_black.svg';
import NewBadgePink from 'src/assets/icons/new_badge_pink.svg';
import MessageBlack from 'src/assets/icons/message_black.svg';
import MessageActiveBlack from 'src/assets/icons/message_active.svg';
import IssueBlack from 'src/assets/icons/issue_black.svg';
import IssueActiveBlack from 'src/assets/icons/issue_active.svg';
import HomeBlack from 'src/assets/icons/home_black.svg';
import HomeActivePurple from 'src/assets/icons/home_active.svg';
import FoldingUpBlack from 'src/assets/icons/folding_up_black.svg';
import FoldingDownBlack from 'src/assets/icons/folding_down_black.svg';
import FlagWhite from 'src/assets/icons/flag_white.svg';
import FavoriteGreen from 'src/assets/icons/favorites_green.svg';
import FavoritesBlack from 'src/assets/icons/favorites_black.svg';
import FavoritesActivePurple from 'src/assets/icons/favorites_active.svg';
import DoubleArrowRightGray from 'src/assets/icons/double-arrow_right_gray.svg';
import DoubleArrowRightBlack from 'src/assets/icons/double-arrow_right_black.svg';
import DoubleArrowLeftGray from 'src/assets/icons/double-arrow_left_gray.svg';
import DoubleArrowLeftBlack from 'src/assets/icons/double-arrow_left_black.svg';
import DeleteGray from 'src/assets/icons/delete_gray.svg';
import DeleteBlack from 'src/assets/icons/delete_black.svg';
import ClosedWhite from 'src/assets/icons/closed_white.svg';
import CheckBoxDefaultPurple from 'src/assets/icons/checkbox_default_purple.svg';
import CheckBoxCheckedPurple from 'src/assets/icons/checkbox_checked_purple.svg';
import CheckWhite from 'src/assets/icons/check_white_circle_white.svg';
import CheckRed from 'src/assets/icons/check_red.svg';
import CategoryLineGray from 'src/assets/icons/category_line_gray.svg';
import BagWhite from 'src/assets/icons/bag_white.svg';
import BagPurple from 'src/assets/icons/bag_purple.svg';
import BagBlack from 'src/assets/icons/bag_black.svg';
import BagActiveBlack from 'src/assets/icons/bag_active.svg';
import ArrowUpWhite from 'src/assets/icons/arrow_up_white.svg';
import ArrowUpRed from 'src/assets/icons/arrow_up_red.svg';
import ArrowUpPurple from 'src/assets/icons/arrow_up_purple.svg';
import ArrowUpGray from 'src/assets/icons/arrow_up_gray.svg';
import ArrowUpBlack from 'src/assets/icons/arrow_up_black.svg';
import ArrowRightWhite from 'src/assets/icons/arrow_right_white.svg';
import ArrowRightRed from 'src/assets/icons/arrow_right_red.svg';
import ArrowRightGray from 'src/assets/icons/arrow_right_gray.svg';
import ArrowRightBlack from 'src/assets/icons/arrow_right_black.svg';
import ArrowLeftWhite from 'src/assets/icons/arrow_left_white.svg';
import ArrowLeftRed from 'src/assets/icons/arrow_left_red.svg';
import ArrowLeftGray from 'src/assets/icons/arrow_left_gray.svg';
import ArrowLeftBlack from 'src/assets/icons/arrow_left_black.svg';
import ArrowDownWhite from 'src/assets/icons/arrow_down_white.svg';
import ArrowDownRed from 'src/assets/icons/arrow_down_red.svg';
import ArrowDownGray from 'src/assets/icons/arrow_down_gray.svg';
import ArrowDownBlack from 'src/assets/icons/arrow_down_black.svg';

// 무엇_속성_색상 순으로 네이밍

export const 화살표_아래_검정색 = ArrowDownBlack;
export const 화살표_위_검정색 = ArrowUpBlack;
export const 화살표_왼쪽_검정색 = ArrowLeftBlack;
export const 화살표_오른쪽_검정색 = ArrowRightBlack;

export const 화살표_아래_빨간색 = ArrowDownRed;
export const 화살표_위_빨간색 = ArrowUpRed;
export const 화살표_왼쪽_빨간색 = ArrowLeftRed;
export const 화살표_오른쪽_빨간색 = ArrowRightRed;

export const 화살표_아래_회색 = ArrowDownGray;
export const 화살표_위_회색 = ArrowUpGray;
export const 화살표_왼쪽_회색 = ArrowLeftGray;
export const 화살표_오른쪽_회색 = ArrowRightGray;

export const 화살표_아래_흰색 = ArrowDownWhite;
export const 화살표_위_흰색 = ArrowUpWhite;
export const 화살표_왼쪽_흰색 = ArrowLeftWhite;
export const 화살표_오른쪽_흰색 = ArrowRightWhite;

export const 화살표_아래_보라색 = ArrowUpPurple;

export const 이중화살표_왼쪽_회색 = DoubleArrowLeftGray;
export const 이중화살표_오른쪽_회색 = DoubleArrowRightGray;

export const 이중화살표_왼쪽_검정색 = DoubleArrowLeftBlack;
export const 이중화살표_오른쪽_검정색 = DoubleArrowRightBlack;

export const 삭제_회색 = DeleteGray;
export const 엑스_검정색 = DeleteBlack;
export const 알림_검정색 = NotificationBlack;
export const 알림_흰색 = NotificationWhite;
export const 검색_검정색 = SearchBlack;
export const 검색_흰색 = SearchWhite;
export const 보이기_회색 = VisibleOnGray;
export const 가리기_회색 = VisibleOffGray;
export const 찾기_배경_검정색 = SearchBackgroundBlack;
export const 더하기_배경_검정색 = PlusBackgroundBlack;
export const 새로운_핑크색 = NewBadgePink;
export const 즐겨찾기_초록색 = FavoriteGreen;
export const 접기_위_검정색 = FoldingUpBlack;
export const 접기_아래_검정색 = FoldingDownBlack;
export const 카테고리_구분선_회색 = CategoryLineGray;

export const 로고_티오더_흰색 = LogoTorder;
export const 로고_티오더_이름_흰색 = LogoTorderName;
export const 로고_티오더_심볼 = TorderLogoSymbol;
export const 로고_애플 = LogoApple;
export const 로고_구글 = LogoGoogle;
export const 로고_카카오톡 = LogoKakao;
export const 로고_네이버 = LogoNaver;

export const 스텝_1단계 = Step1;
export const 스텝_2단계 = Step2;
export const 스텝_3단계 = Step3;

export const 체크_빨간색 = CheckRed;
export const 체크_흰색_바탕_빨간색 = CheckWhite;
export const 체크박스_기본_보라색 = CheckBoxDefaultPurple;
export const 체크박스_체크_보라색 = CheckBoxCheckedPurple;

export const 가방_흰색 = BagWhite;
export const 가방_보라색 = BagPurple;
export const 깃발_흰색 = FlagWhite;
export const 유저_흰색 = UserWhite;
export const 설정_흰색 = SettingWhite;
export const 열기_흰색 = OpenWhite;
export const 열기_네이비 = OpenNavy;
export const 닫기_흰색 = ClosedWhite;
export const 토글_활성화_검정색 = ToggleOnBlack;
export const 토글_비활성화_검정색 = ToggleOffBlack;

export const 홈_검정색 = HomeBlack;
export const 홈_활성화_보라색 = HomeActivePurple;
export const 유저_검정색 = UserBlack;
export const 유저_활성화_보라색 = UserActivePurple;
export const 가방_검정색 = BagBlack;
export const 가방_활성화_보라색 = BagActiveBlack;
export const 즐겨찾기_검정색 = FavoritesBlack;
export const 즐겨찾기_활성화_보라색 = FavoritesActivePurple;
export const 메세지_검정색 = MessageBlack;
export const 메세지_활성화_보라색 = MessageActiveBlack;
export const 이슈_검정색 = IssueBlack;
export const 이슈_활성화_보라색 = IssueActiveBlack;
export const 설정_검정색 = SettingBlack;
export const 설정_활성화_보라색 = SettingActiveBlack;
