export const productResultData = {
  data: [
    {
      categoryCode: '110731',
      id: 'iceCream',
      name: '아이스크림',
      languageName: { ko: '아이스크림', en: 'Ice Cream', jp: 'アイスクリーム', zh_hans: '冰淇淋', zh_hant: '雪糕' },
      code: '110733',
      productList: [
        {
          name: '바닐라 소프트 아이스크림',
          languageName: {
            ko: '바닐라 소프트 아이스크림',
            en: 'Vanilla Soft Serve Ice Cream',
            jp: 'バニラソフトクリーム',
            zh_hans: '香草软冰淇淋',
            zh_hant: '香草软冰淇淋',
          },
          code: 'CJUGH-24010513',
          html: '부드러운 바닐라 맛의 소프트 아이스크림 위에 달콤한 초코볼이 올라가 있어 더욱 맛있게 드실 수 있습니다.',
          image: 'https://hyatt.static.torder.co.kr/INFRA_CAFE8002/goods/CJUGH-24010513/1682234020item_700X700.png',
          price: 9000,
          countryOfOrigin: '',
        },
        {
          name: '초콜릿 소프트 아이스크림',
          languageName: {
            ko: '초콜릿 소프트 아이스크림',
            en: 'Chocolate Soft Serve Ice Cream',
            jp: 'チョコレートソフトクリーム',
            zh_hans: '巧克力软冰淇淋',
            zh_hant: '巧克力软冰淇淋',
          },
          code: 'CJUGH-24010514',
          html: '진한 초콜릿 맛의 소프트 아이스크림 위에 달콤한 초코볼이 올라가 있어 더욱 맛있게 드실 수 있습니다.',
          image: 'https://hyatt.static.torder.co.kr/INFRA_CAFE8002/goods/CJUGH-24010514/1682335972item_700X700.png',
          price: 9000,
          countryOfOrigin: '',
        },
        {
          name: '바닐라 초콜릿 소프트 아이스크림',
          languageName: {
            ko: '바닐라 초콜릿 소프트 아이스크림',
            en: 'Vanilla & Chocolate Twist Soft Serve Ice Cream',
            jp: 'ミックス ソフトクリーム',
            zh_hans: '',
            zh_hant: '',
          },
          code: 'CJUGH-24010515',
          html: '부드러운 바닐라와 진한 초콜릿이 섞인 소프트 아이스크림이 위에 달콤한 초코볼이 올라가 있어 더욱 맛있게 드실 수 있습니다.',
          image: 'https://hyatt.static.torder.co.kr/INFRA_CAFE8002/goods/CJUGH-24010515/1682336025item_700X700.png',
          price: 9000,
          countryOfOrigin: '',
        },
        {
          name: '레몬 소르베',
          languageName: {
            ko: '레몬 소르베',
            en: 'Lemon Sorbet',
            jp: 'レモンソルベ',
            zh_hans: '柠檬冰淇淋',
            zh_hant: '檸檬雪糕',
          },
          code: 'CJUGH-24010509',
          html: '레몬으로 만든 상큼한 홈메이드 소르베입니다.',
          image: 'https://hyatt.static.torder.co.kr/INFRA_CAFE8002/goods/CJUGH-24010509/1676350336item_700X700.png',
          price: 9000,
          countryOfOrigin: '',
        },
      ],
    },
  ],
};
